In [ ]:
!pip3 install  numpy

In [ ]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available")
else:
    device = torch.device("cpu")
    print("GPU is not available")

In [ ]:
%pip install pandas openpyxl

In [1]:
import pandas as pd
import numpy as np

# Excelファイルを読み込む
file_path =  '/home/alkalinemoe/psych_model_scripts/1-41800_article.xlsx'
df = pd.read_excel(file_path, engine='openpyxl')

# データフレームを表示する
df.head()

,sex,age,Duration (in seconds),回答（分）,1~10_1,1~10_2,1~10_3,1~10_4,1~10_5,1~10_6,...,981~990_5,981~990_6,981~990_7,991~1000_1,991~1000_2,991~1000_3,991~1000_4,991~1000_5,991~1000_6,991~1000_7
0,NaN,NaN,時間（秒単位）,回答（分）,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...
1,男性,36.0,2781,46.35,2,2,3,4,2,3,...,4,3,3,3,2,3,2,4,3,3
2,男性,28.0,976,16.266667,2,2,2,2,2,2,...,3,3,3,2,2,2,3,3,3,3
3,女性,29.0,2824,47.066667,2,1,2,2,4,2,...,4,1,1,1,1,1,3,2,1,1
4,女性,44.0,1565,26.083333,3,3,2,4,4,4,...,2,3,3,2,2,2,3,2,2,2

In [2]:
df.shape

(8, 704)

In [3]:
# Excelファイルのパスを指定
file_path = '/home/alkalinemoe/psych_model_scripts/1-41800_article.xlsx'

# Excelファイルのシート名をすべて取得
sheet_names = pd.ExcelFile(file_path).sheet_names

# 各シートをデータフレームに変換し、リストに格納
dataframes = [pd.read_excel(file_path, sheet_name=sheet) for sheet in sheet_names]

# リスト内のすべてのデータフレームを統合
combined_dataframe = pd.concat(dataframes, ignore_index=True)

In [4]:
print(len(dataframes))
column_names = df.columns.tolist()
print(column_names)

42
['sex', 'age', 'Duration (in seconds)', '回答（分）', '1~10_1', '1~10_2', '1~10_3', '1~10_4', '1~10_5', '1~10_6', '1~10_7', '11~20_1', '11~20_2', '11~20_3', '11~20_4', '11~20_5', '11~20_6', '11~20_7', '21~30_1', '21~30_2', '21~30_3', '21~30_4', '21~30_5', '21~30_6', '21~30_7', '31~40_1', '31~40_2', '31~40_3', '31~40_4', '31~40_5', '31~40_6', '31~40_7', '41~50_1', '41~50_2', '41~50_3', '41~50_4', '41~50_5', '41~50_6', '41~50_7', '51~60_1', '51~60_2', '51~60_3', '51~60_4', '51~60_5', '51~60_6', '51~60_7', 'Q64_1', 'Q64_2', 'Q64_3', 'Q64_4', 'Q64_5', 'Q64_6', 'Q64_7', 'Q74_1', 'Q74_2', 'Q74_3', 'Q74_4', 'Q74_5', 'Q74_6', 'Q74_7', 'Q84_1', 'Q84_2', 'Q84_3', 'Q84_4', 'Q84_5', 'Q84_6', 'Q84_7', 'Q95_1', 'Q95_2', 'Q95_3', 'Q95_4', 'Q95_5', 'Q95_6', 'Q95_7', 'Q104_1', 'Q104_2', 'Q104_3', 'Q104_4', 'Q104_5', 'Q104_6', 'Q104_7', 'Q14_1', 'Q14_2', 'Q14_3', 'Q14_4', 'Q14_5', 'Q14_6', 'Q14_7', 'Q15_1', 'Q15_2', 'Q15_3', 'Q15_4', 'Q15_5', 'Q15_6', 'Q15_7', '131~140_1', '131~140_2', '131~140_3', '131~140_4', '131~140_5', '131~140_6', '131~140_7', '141~150_1', '141~150_2', '141~150_3', '141~150_4', '141~150_5', '141~150_6', '141~150_7', '151~160_1', '151~160_2', '151~160_3', '151~160_4', '151~160_5', '151~160_6', '151~160_7', '161~170_1', '161~170_2', '161~170_3', '161~170_4', '161~170_5', '161~170_6', '161~170_7', '171~180_1', '171~180_2', '171~180_3', '171~180_4', '171~180_5', '171~180_6', '171~180_7', '181~190_1', '181~190_2', '181~190_3', '181~190_4', '181~190_5', '181~190_6', '181~190_7', '191~200_1', '191~200_2', '191~200_3', '191~200_4', '191~200_5', '191~200_6', '191~200_7', '201~210_1', '201~210_2', '201~210_3', '201~210_4', '201~210_5', '201~210_6', '201~210_7', '211~220_1', '211~220_2', '211~220_3', '211~220_4', '211~220_5', '211~220_6', '211~220_7', '221~230_1', '221~230_2', '221~230_3', '221~230_4', '221~230_5', '221~230_6', '221~230_7', '231~240_1', '231~240_2', '231~240_3', '231~240_4', '231~240_5', '231~240_6', '231~240_7', '241~250_1', '241~250_2', '241~250_3', '241~250_4', '241~250_5', '241~250_6', '241~250_7', '251~260_1', '251~260_2', '251~260_3', '251~260_4', '251~260_5', '251~260_6', '251~260_7', '261~270_1', '261~270_2', '261~270_3', '261~270_4', '261~270_5', '261~270_6', '261~270_7', '271~280_1', '271~280_2', '271~280_3', '271~280_4', '271~280_5', '271~280_6', '271~280_7', '281~290_1', '281~290_2', '281~290_3', '281~290_4', '281~290_5', '281~290_6', '281~290_7', '291~300_1', '291~300_2', '291~300_3', '291~300_4', '291~300_5', '291~300_6', '291~300_7', '301~310_1', '301~310_2', '301~310_3', '301~310_4', '301~310_5', '301~310_6', '301~310_7', '311~320_1', '311~320_2', '311~320_3', '311~320_4', '311~320_5', '311~320_6', '311~320_7', '321~330_1', '321~330_2', '321~330_3', '321~330_4', '321~330_5', '321~330_6', '321~330_7', '331~340_1', '331~340_2', '331~340_3', '331~340_4', '331~340_5', '331~340_6', '331~340_7', '341~350_1', '341~350_2', '341~350_3', '341~350_4', '341~350_5', '341~350_6', '341~350_7', '351~360_1', '351~360_2', '351~360_3', '351~360_4', '351~360_5', '351~360_6', '351~360_7', '361~370_1', '361~370_2', '361~370_3', '361~370_4', '361~370_5', '361~370_6', '361~370_7', '371~380_1', '371~380_2', '371~380_3', '371~380_4', '371~380_5', '371~380_6', '371~380_7', '381~390_1', '381~390_2', '381~390_3', '381~390_4', '381~390_5', '381~390_6', '381~390_7', '391~400_1', '391~400_2', '391~400_3', '391~400_4', '391~400_5', '391~400_6', '391~400_7', '401~410_1', '401~410_2', '401~410_3', '401~410_4', '401~410_5', '401~410_6', '401~410_7', '411~420_1', '411~420_2', '411~420_3', '411~420_4', '411~420_5', '411~420_6', '411~420_7', '421~430_1', '421~430_2', '421~430_3', '421~430_4', '421~430_5', '421~430_6', '421~430_7', '431~440_1', '431~440_2', '431~440_3', '431~440_4', '431~440_5', '431~440_6', '431~440_7', 'Q47_1', 'Q47_2', 'Q47_3', 'Q47_4', 'Q47_5', 'Q47_6', 'Q47_7', 'Q48_1', 'Q48_2', 'Q48_3', 'Q48_4', 'Q48_5', 'Q48_6', 'Q48_7', 'Q49_1', 'Q49_2', 'Q49_3', 'Q49_4', 'Q49_5', 'Q49_6', 'Q49_7', 'Q50_1', 'Q50_2', 'Q50_3', 'Q50_4', 'Q50_5', 'Q50_6', 'Q50_7', 'Q51_1', 'Q51_2', 'Q51_3', 'Q51_4', 'Q51_5', 'Q51_6', 'Q51_7', 'Q52_1', 'Q52_2', 'Q52_3', 'Q52_4', 'Q52_5', 'Q52_6', 'Q52_7', 'Q53_1', 'Q53_2', 'Q53_3', 'Q53_4', 'Q53_5', 'Q53_6', 'Q53_7', 'Q54_1', 'Q54_2', 'Q54_3', 'Q54_4', 'Q54_5', 'Q54_6', 'Q54_7', 'Q55_1', 'Q55_2', 'Q55_3', 'Q55_4', 'Q55_5', 'Q55_6', 'Q55_7', 'Q56_1', 'Q56_2', 'Q56_3', 'Q56_4', 'Q56_5', 'Q56_6', 'Q56_7', '541~550_1', '541~550_2', '541~550_3', '541~550_4', '541~550_5', '541~550_6', '541~550_7', 'Q58_1', 'Q58_2', 'Q58_3', 'Q58_4', 'Q58_5', 'Q58_6', 'Q58_7', 'Q59_1', 'Q59_2', 'Q59_3', 'Q59_4', 'Q59_5', 'Q59_6', 'Q59_7', 'Q60_1', 'Q60_2', 'Q60_3', 'Q60_4', 'Q60_5', 'Q60_6', 'Q60_7', 'Q61_1', 'Q61_2', 'Q61_3', 'Q61_4', 'Q61_5', 'Q61_6', 'Q61_7', 'Q62_1', 'Q62_2', 'Q62_3', 'Q62_4', 'Q62_5', 'Q62_6', 'Q62_7', 'Q63_1', 'Q63_2', 'Q63_3', 'Q63_4', 'Q63_5', 'Q63_6', 'Q63_7', 'Q64_1.1', 'Q64_2.1', 'Q64_3.1', 'Q64_4.1', 'Q64_5.1', 'Q64_6.1', 'Q64_7.1', 'Q65_1', 'Q65_2', 'Q65_3', 'Q65_4', 'Q65_5', 'Q65_6', 'Q65_7', 'Q66_1', 'Q66_2', 'Q66_3', 'Q66_4', 'Q66_5', 'Q66_6', 'Q66_7', 'Q67_1', 'Q67_2', 'Q67_3', 'Q67_4', 'Q67_5', 'Q67_6', 'Q67_7', 'Q68_1', 'Q68_2', 'Q68_3', 'Q68_4', 'Q68_5', 'Q68_6', 'Q68_7', 'Q69_1', 'Q69_2', 'Q69_3', 'Q69_4', 'Q69_5', 'Q69_6', 'Q69_7', 'Q70_1', 'Q70_2', 'Q70_3', 'Q70_4', 'Q70_5', 'Q70_6', 'Q70_7', 'Q71_1', 'Q71_2', 'Q71_3', 'Q71_4', 'Q71_5', 'Q71_6', 'Q71_7', 'Q72_1', 'Q72_2', 'Q72_3', 'Q72_4', 'Q72_5', 'Q72_6', 'Q72_7', 'Q73_1', 'Q73_2', 'Q73_3', 'Q73_4', 'Q73_5', 'Q73_6', 'Q73_7', 'Q74_1.1', 'Q74_2.1', 'Q74_3.1', 'Q74_4.1', 'Q74_5.1', 'Q74_6.1', 'Q74_7.1', 'Q75_1', 'Q75_2', 'Q75_3', 'Q75_4', 'Q75_5', 'Q75_6', 'Q75_7', 'Q76_1', 'Q76_2', 'Q76_3', 'Q76_4', 'Q76_5', 'Q76_6', 'Q76_7', 'Q77_1', 'Q77_2', 'Q77_3', 'Q77_4', 'Q77_5', 'Q77_6', 'Q77_7', 'Q78_1', 'Q78_2', 'Q78_3', 'Q78_4', 'Q78_5', 'Q78_6', 'Q78_7', 'Q79_1', 'Q79_2', 'Q79_3', 'Q79_4', 'Q79_5', 'Q79_6', 'Q79_7', 'Q80_1', 'Q80_2', 'Q80_3', 'Q80_4', 'Q80_5', 'Q80_6', 'Q80_7', '781~790_1', '781~790_2', '781~790_3', '781~790_4', '781~790_5', '781~790_6', '781~790_7', '791~800_1', '791~800_2', '791~800_3', '791~800_4', '791~800_5', '791~800_6', '791~800_7', '801~810_1', '801~810_2', '801~810_3', '801~810_4', '801~810_5', '801~810_6', '801~810_7', '811~820_1', '811~820_2', '811~820_3', '811~820_4', '811~820_5', '811~820_6', '811~820_7', '821~830_1', '821~830_2', '821~830_3', '821~830_4', '821~830_5', '821~830_6', '821~830_7', '831~840_1', '831~840_2', '831~840_3', '831~840_4', '831~840_5', '831~840_6', '831~840_7', '841~850_1', '841~850_2', '841~850_3', '841~850_4', '841~850_5', '841~850_6', '841~850_7', '851~860_1', '851~860_2', '851~860_3', '851~860_4', '851~860_5', '851~860_6', '851~860_7', '861~870_1', '861~870_2', '861~870_3', '861~870_4', '861~870_5', '861~870_6', '861~870_7', '871~880_1', '871~880_2', '871~880_3', '871~880_4', '871~880_5', '871~880_6', '871~880_7', '881~890_1', '881~890_2', '881~890_3', '881~890_4', '881~890_5', '881~890_6', '881~890_7', 'Q92_1', 'Q92_2', 'Q92_3', 'Q92_4', 'Q92_5', 'Q92_6', 'Q92_7', 'Q93_1', 'Q93_2', 'Q93_3', 'Q93_4', 'Q93_5', 'Q93_6', 'Q93_7', '911~920_1', '911~920_2', '911~920_3', '911~920_4', '911~920_5', '911~920_6', '911~920_7', '921~930_1', '921~930_2', '921~930_3', '921~930_4', '921~930_5', '921~930_6', '921~930_7', '931~940_1', '931~940_2', '931~940_3', '931~940_4', '931~940_5', '931~940_6', '931~940_7', '941~950_1', '941~950_2', '941~950_3', '941~950_4', '941~950_5', '941~950_6', '941~950_7', '951~960_1', '951~960_2', '951~960_3', '951~960_4', '951~960_5', '951~960_6', '951~960_7', '961~970_1', '961~970_2', '961~970_3', '961~970_4', '961~970_5', '961~970_6', '961~970_7', '971~980_1', '971~980_2', '971~980_3', '971~980_4', '971~980_5', '971~980_6', '971~980_7', '981~990_1', '981~990_2', '981~990_3', '981~990_4', '981~990_5', '981~990_6', '981~990_7', '991~1000_1', '991~1000_2', '991~1000_3', '991~1000_4', '991~1000_5', '991~1000_6', '991~1000_7']

In [5]:
# 各DataFrameの時間秒列を結合したシリーズを作成
duration_series = pd.concat([df['Duration (in seconds)'] for df in dataframes], ignore_index=True)
# 数値に変換できる要素のみを選択して、浮動小数点数に変換
duration_series = pd.to_numeric(duration_series, errors='coerce')
duration_series=duration_series.dropna()
# 平均値と標準偏差を計算
mean = np.mean(duration_series)
std = np.std(duration_series)

# 結果を表示
print("Mean:", mean)
print("Std:", std)

Mean: 3036.847619047619
Std: 1553.755706611456

In [6]:
import re
r = (
    None,
    re.compile(r'^(.+) - 1.[\s\t]*喜びを感じた$'),
    re.compile(r'^(.+) - 2.[\s\t]*恐怖を感じた$'),
    re.compile(r'^(.+) - 3.[\s\t]*驚きを感じた$'),
    re.compile(r'^(.+) - 4.[\s\t]*信頼できる情報と感じた$'),
    re.compile(r'^(.+) - 5.[\s\t]*曖昧な情報と感じた$'),
    re.compile(r'^(.+) - 6.[\s\t]*何かの意図をもって書かれたと感じた$'),
    re.compile(r'^(.+) - 7.[\s\t]*経済に期待がもてると感じた$'),
)
repl = lambda m: m.group(1)

In [7]:
df=dataframes[0]
df

,sex,age,Duration (in seconds),回答（分）,1~10_1,1~10_2,1~10_3,1~10_4,1~10_5,1~10_6,...,981~990_5,981~990_6,981~990_7,991~1000_1,991~1000_2,991~1000_3,991~1000_4,991~1000_5,991~1000_6,991~1000_7
0,NaN,NaN,時間（秒単位）,回答（分）,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...
1,男性,36.0,2781,46.35,2,2,3,4,2,3,...,4,3,3,3,2,3,2,4,3,3
2,男性,28.0,976,16.266667,2,2,2,2,2,2,...,3,3,3,2,2,2,3,3,3,3
3,女性,29.0,2824,47.066667,2,1,2,2,4,2,...,4,1,1,1,1,1,3,2,1,1
4,女性,44.0,1565,26.083333,3,3,2,4,4,4,...,2,3,3,2,2,2,3,2,2,2
5,男性,35.0,2417,40.283333,3,2,2,3,2,3,...,2,2,3,3,2,2,4,2,3,3
6,NaN,NaN,NaN,M,2.4,2,2.2,3,2.8,2.8,...,3,2.4,2.6,2.2,1.8,2,3,2.6,2.4,2.4
7,NaN,NaN,NaN,SD,0.489898,0.632456,0.4,0.894427,0.979796,0.748331,...,0.894427,0.8,0.8,0.748331,0.4,0.632456,0.632456,0.8,0.8,0.8

In [11]:
df=dataframes[0]

def transform_dataframe(df):
    x=1200
    # 数値を抽出するための正規表現パターン
    pattern = r'(\d+)'

    # 数値部分を抽出して新しい列を作成
    # 整数型の値として解釈できるものを選択し、x 秒以上の行を削除
    df['Duration_numeric'] = pd.to_numeric(df['Duration (in seconds)'], errors='coerce')
    # x秒以上の行を削除
    df = df[(df['Duration_numeric'] > x)|(df['Duration_numeric'].isna())]
    data=df.T.iloc[4:,:]
    data = data[data.index!= 'Duration_numeric']
    data['ids'] = data.index.str.split(r'_', expand=False)

    # 新しい列にYの値を格納
    data['id_range'] = data['ids'].apply(lambda s: s[0])
    data['seq'] = data['ids'].apply(lambda s: s[1])
    data['text'] = data[0]
    for i in range(1, 8):
            data['text'] = data['text'].str.replace(r[i], repl, regex=True)
    return data

In [12]:
transform_dataframe(df)

,0,1,3,4,5,6,7,ids,id_range,seq,text
1~10_1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,2,3,3,2.4,0.489898,"[1~10, 1]",1~10,1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...
1~10_2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,1,3,2,2,0.632456,"[1~10, 2]",1~10,2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...
1~10_3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,3,2,2,2,2.2,0.4,"[1~10, 3]",1~10,3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...
1~10_4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,4,2,4,3,3,0.894427,"[1~10, 4]",1~10,4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...
1~10_5,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,4,4,2,2.8,0.979796,"[1~10, 5]",1~10,5,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...
...,...,...,...,...,...,...,...,...,...,...,...
991~1000_3,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,3,1,2,2,2,0.632456,"[991~1000, 3]",991~1000,3,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...
991~1000_4,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,2,3,3,4,3,0.632456,"[991~1000, 4]",991~1000,4,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...
991~1000_5,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,4,2,2,2,2.6,0.8,"[991~1000, 5]",991~1000,5,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...
991~1000_6,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,3,1,2,3,2.4,0.8,"[991~1000, 6]",991~1000,6,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...
991~1000_7,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...,3,1,2,3,2.4,0.8,"[991~1000, 7]",991~1000,7,・「中日５−０阪神」（３０日、ナゴヤドーム） 阪神が今季２度目の完封負けを喫した。・「巨人５...

In [13]:
#42個のエクセルから読み込んだdfにtransform_dataframe関数を適用させ、新しいdataframeのリストを作成
transformed_dataframes = [transform_dataframe(df) for df in dataframes]

In [14]:
print(len(transformed_dataframes))
print(transformed_dataframes[0].shape)
for df in transformed_dataframes:
    print(df.shape)

42
(700, 11)
(700, 11)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 10)
(700, 12)
(700, 11)
(700, 12)
(700, 12)
(700, 12)
(700, 11)
(700, 11)
(700, 12)
(700, 12)
(700, 11)
(700, 12)
(700, 12)
(700, 12)
(700, 11)
(700, 11)
(700, 12)
(700, 12)
(700, 12)
(700, 11)
(700, 12)
(700, 11)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 11)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(700, 12)
(560, 12)

In [15]:
combined_df = pd.concat(transformed_dataframes, ignore_index=True)

In [16]:
combined_df.shape

(29260, 12)

In [17]:
missing_values = combined_df.isnull().sum()
print(missing_values)

0              0
1           4200
3           1400
4            700
5              0
6              0
7              0
ids            0
id_range       0
seq            0
text           0
2           2100
dtype: int64

In [18]:
combined_df.head()

,0,1,3,4,5,6,7,ids,id_range,seq,text,2
0,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,2,3,3,2.4,0.489898,"[1~10, 1]",1~10,1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN
1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,1,3,2,2,0.632456,"[1~10, 2]",1~10,2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN
2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,3,2,2,2,2.2,0.4,"[1~10, 3]",1~10,3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN
3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,4,2,4,3,3,0.894427,"[1~10, 4]",1~10,4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN
4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,4,4,2,2.8,0.979796,"[1~10, 5]",1~10,5,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN

In [19]:
import numpy as np
# 規則に基づいてid列に値を挿入
id_values = []
current_id = 0
for seq_value in range(1,len(combined_df)+1):
    if seq_value%7 == 1:
            current_id += 1
    id_values.append(current_id)
    
print(len(id_values))
combined_df["id"]=id_values
combined_df
#id_values

29260

,0,1,3,4,5,6,7,ids,id_range,seq,text,2,id
0,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,2,3,3,2.4,0.489898,"[1~10, 1]",1~10,1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN,1
1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,1,3,2,2,0.632456,"[1~10, 2]",1~10,2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN,1
2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,3,2,2,2,2.2,0.4,"[1~10, 3]",1~10,3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN,1
3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,4,2,4,3,3,0.894427,"[1~10, 4]",1~10,4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN,1
4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,4,4,2,2.8,0.979796,"[1~10, 5]",1~10,5,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29255,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,1,3,1,3,2.2,0.979796,"[41791-41800, 3]",41791-41800,3,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,3,4180
29256,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,4,3,2,3,3,0.632456,"[41791-41800, 4]",41791-41800,4,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,3,4180
29257,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,2,3,4,3,3,0.632456,"[41791-41800, 5]",41791-41800,5,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,3,4180
29258,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,2,4,1,3,2.6,1.019804,"[41791-41800, 6]",41791-41800,6,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,3,4180
29259,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,2,3,1,3,2.2,0.748331,"[41791-41800, 7]",41791-41800,7,・大相撲の時津風親方（元前頭時津海）が29日夜、急性膵炎（すいえん）により手術を受けることが...,2,4180

In [20]:
unique_values = combined_df["seq"].value_counts()
print(unique_values)
combined_df["seq"] = combined_df["seq"].replace("1.1", 1)
combined_df["seq"] = combined_df["seq"].replace("2.1", 2)
combined_df["seq"] = combined_df["seq"].replace("3.1", 3)
combined_df["seq"] = combined_df["seq"].replace("4.1", 4)
combined_df["seq"] = combined_df["seq"].replace("5.1", 5)
combined_df["seq"] = combined_df["seq"].replace("6.1", 6)
combined_df["seq"] = combined_df["seq"].replace("7.1", 7)
combined_df["seq"] = combined_df["seq"].astype(int)
unique_values = combined_df["seq"].value_counts()
print(unique_values)

seq
1      4177
2      4177
3      4177
4      4177
5      4177
6      4177
7      4177
1.1       3
2.1       3
3.1       3
4.1       3
5.1       3
6.1       3
7.1       3
Name: count, dtype: int64
seq
1    4180
2    4180
3    4180
4    4180
5    4180
6    4180
7    4180
Name: count, dtype: int64

In [21]:
# 列名を変更する前に、現在の列名を取得します
column_names = combined_df.columns.tolist()

# 5列目と6列目の名前を変更します
# Pythonは0から数えるので、5列目と6列目はそれぞれインデックス4と5になります
column_names[5] = 'mean'
column_names[6] = 'sd'

# 新しい列名を適用します
combined_df.columns = column_names

In [22]:
combined_df=combined_df[combined_df["sd"]<1.4]

In [23]:
combined_df.shape

(28786, 13)

In [24]:
import re
from pyknp import Juman
from tqdm import tqdm
import mojimoji

# 形態素解析器のインスタンスを作成
jumanpp = Juman()

# tqdmをPandasに組み込む
tqdm.pandas()

# テキストを文単位に分割し、【】で囲まれている部分を削除、全角変換、形態素解析を行う
def process_text(text):
    # テキストを全角に変換
    text = mojimoji.han_to_zen(text)
    
    # 【】で囲まれている部分を削除
    text = re.sub('【.*?】', '', text)

    # テキストを文単位に分割
    sentences = re.split('。|\n', text)

    # 文が20文字未満のものを除外
    sentences = [sentence for sentence in sentences if len(sentence) >= 20]

    # 各文に形態素解析を適用
    words = [' '.join([mrph.midasi for mrph in jumanpp.analysis(sentence.replace('^', '＾')).mrph_list()]) for sentence in sentences]

    return ' '.join(words)

combined_df['text'] = combined_df['text'].progress_apply(process_text)

100%|██████████| 28786/28786 [08:39<00:00, 55.38it/s]
/tmp/ipykernel_638820/2568028541.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['text'] = combined_df['text'].progress_apply(process_text)

In [25]:
combined_df.head()

,0,1,3,4,5,mean,sd,ids,id_range,seq,text,2,id
0,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,2,3,3,2.4,0.489898,"[1~10, 1]",1~10,1,・ 「 ビジネス 」 の 一 押し 「 Ｂｉｚ レーダー 」 は 話題 の ビジネス ニ...,NaN,1
1,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,1,3,2,2,0.632456,"[1~10, 2]",1~10,2,・ 「 ビジネス 」 の 一 押し 「 Ｂｉｚ レーダー 」 は 話題 の ビジネス ニ...,NaN,1
2,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,3,2,2,2,2.2,0.4,"[1~10, 3]",1~10,3,・ 「 ビジネス 」 の 一 押し 「 Ｂｉｚ レーダー 」 は 話題 の ビジネス ニ...,NaN,1
3,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,4,2,4,3,3,0.894427,"[1~10, 4]",1~10,4,・ 「 ビジネス 」 の 一 押し 「 Ｂｉｚ レーダー 」 は 話題 の ビジネス ニ...,NaN,1
4,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,4,4,2,2.8,0.979796,"[1~10, 5]",1~10,5,・ 「 ビジネス 」 の 一 押し 「 Ｂｉｚ レーダー 」 は 話題 の ビジネス ニ...,NaN,1

In [26]:
#seqの値によって、dfを分解
combined_df_seq=[[]for _ in range(8)]
for i in range(1,8):
    combined_df_seq[i]=combined_df[combined_df["seq"]==i]
    print(len(combined_df_seq[i]))

4164
4027
4039
4168
4131
4109
4148

In [30]:
combined_df_seq[1].head()

,0,1,3,4,5,mean,sd,ids,id_range,seq,text,2,id
0,・「ビジネス」の一押し 「Bizレーダー」は話題のビジネスニュースの内幕や、企業の隠れた思惑...,2,2,3,3,2.4,0.489898,"[1~10, 1]",1~10,1,・ 「 ビジネス 」 の 一 押し 「 Ｂｉｚ レーダー 」 は 話題 の ビジネス ニ...,NaN,1
7,・ジャカルタ＝鈴木淳、新型コロナウイルスの集団感染が起きたクルーズ船「ダイヤモンド・プリンセ...,2,2,2,4,2.6,0.8,"[11~20, 1]",11~20,1,・ ジャカルタ ＝ 鈴木 淳 、 新型 コロナ ウイルス の 集団 感染 が 起きた クルー...,NaN,2
14,・ベルリン＝石川潤、国際決済銀行（ＢＩＳ）は１日、新型コロナウイルスがもたらす影響への「突然...,2,1,2,3,2.2,0.748331,"[21~30, 1]",21~30,1,・ ベルリン ＝ 石川 潤 、 国際 決済 銀行 （ ＢＩＳ ） は １ 日 、 新型 コロ...,NaN,3
21,・企業のＭ＆Ａ（合併・買収）仲介のストライクは３月、買収を検討する企業のために売り手企業を探...,2,2,2,2,2.2,0.4,"[31~40, 1]",31~40,1,・ 企業 の Ｍ＆Ａ （ 合併 ・ 買収 ） 仲介 の ストライク は ３ 月 、 買収 を...,NaN,4
28,・医薬・化成品の商社ＣＢＣ（東京・中央）はインドで医療機器を販売するボストン・アイビー・ヘル...,2,1,3,2,2.2,0.748331,"[41~50, 1]",41~50,1,・ 医薬 ・ 化成 品 の 商社 ＣＢＣ （ 東京 ・ 中央 ） は インド で 医療 機器...,NaN,5

In [27]:
from sklearn.model_selection import train_test_split
sentences_train_old_all=[[]for _ in range(8)]
labels_train_old_all=[[]for _ in range(8)]
sentences_dev_old_all=[[]for _ in range(8)]
labels_dev_old_all=[[]for _ in range(8)]
sentences_test_old_all=[[]for _ in range(8)]
labels_test_old_all=[[]for _ in range(8)]

for i in range(1,8):

    # 訓練データ、検証データ、テストデータに分割する
    train_val, test = train_test_split(combined_df_seq[i], test_size=0.1, random_state=42)
    train, val = train_test_split(train_val, test_size=0.111, random_state=42)

    # 訓練データ、検証データ、テストデータのサイズを表示する
    print(f"訓練データのサイズ: {len(train)}, 検証データのサイズ: {len(val)}, テストデータのサイズ: {len(test)}")
    
    for index, row in train.iterrows():
        sentences_train_old_all[i].append(row['text'])
        labels_train_old_all[i].append(row['mean'])
    for index, row in val.iterrows():
        sentences_dev_old_all[i].append(row['text'])
        labels_dev_old_all[i].append(row['mean'])
    for index, row in test.iterrows():
        sentences_test_old_all[i].append(row['text'])
        labels_test_old_all[i].append(row['mean'])

訓練データのサイズ: 3331, 検証データのサイズ: 416, テストデータのサイズ: 417
訓練データのサイズ: 3221, 検証データのサイズ: 403, テストデータのサイズ: 403
訓練データのサイズ: 3231, 検証データのサイズ: 404, テストデータのサイズ: 404
訓練データのサイズ: 3334, 検証データのサイズ: 417, テストデータのサイズ: 417
訓練データのサイズ: 3304, 検証データのサイズ: 413, テストデータのサイズ: 414
訓練データのサイズ: 3287, 検証データのサイズ: 411, テストデータのサイズ: 411
訓練データのサイズ: 3318, 検証データのサイズ: 415, テストデータのサイズ: 415

In [31]:
labels_test_old_all[1]

[2.4,
 2,
 2,
 2.6,
 2.2,
 2.4,
 1.8,
 2.8,
 2.6,
 2.4,
 2,
 2.4,
 2.2,
 2.8,
 2,
 2,
 2.2,
 2.2,
 2,
 2,
 2.4,
 2.2,
 2.4,
 2.2,
 1.8,
 1.2,
 2.4,
 1.8,
 2.4,
 2.6,
 2,
 1.4,
 2.2,
 3,
 2.6,
 2,
 1.6,
 2.4,
 1.6,
 1.8,
 2.4,
 2,
 2.4,
 2,
 3,
 2.4,
 2.2,
 2,
 1.4,
 2.2,
 2.2,
 2,
 1.8,
 1.8,
 2.2,
 2.6,
 2,
 1.8,
 3.2,
 2.4,
 1.6,
 1.6,
 2,
 2.8,
 2.2,
 2.2,
 2,
 2.6,
 2,
 2.8,
 1.6,
 1.8,
 1.8,
 2.6,
 2.6,
 2,
 2.4,
 2.6,
 2,
 2.4,
 1.6,
 1.8,
 1.8,
 2,
 2.2,
 2,
 2.6,
 1.8,
 2,
 2.8,
 2.4,
 1.8,
 2,
 2,
 2.6,
 2,
 2,
 1.8,
 2.8,
 1.4,
 2.2,
 2.2,
 1.6,
 2.8,
 1.6,
 1.6,
 1.4,
 1.8,
 2.8,
 1.6,
 1.8,
 1.8,
 3.8,
 1.2,
 1.2,
 1.6,
 2.2,
 2.2,
 2.6,
 2,
 2,
 2.2,
 1.4,
 2.6,
 2.4,
 2.4,
 2.2,
 2.2,
 2,
 1.6,
 2,
 1.6,
 1.6,
 2.2,
 2.2,
 1.4,
 1.8,
 2.4,
 2.4,
 2.4,
 2.2,
 2.4,
 2.8,
 2.2,
 1.8,
 2.4,
 2,
 2,
 2.2,
 1.6,
 1.8,
 1.8,
 2.6,
 2,
 2,
 3,
 2.6,
 2.6,
 2,
 1.8,
 2,
 2.6,
 2,
 2.6,
 2,
 1.8,
 2.2,
 2,
 1.6,
 2.2,
 2.2,
 2.4,
 2.4,
 1.8,
 2.6,
 2,
 2,
 2.8,
 2,
 2.6,
 2,
 2.4,
 2.2,
 1.8,
 2.8,
 1.6,
 2.6,
 2,
 2.4,
 2.4,
 2,
 2,
 1.6,
 1.4,
 1.8,
 1.8,
 2.6,
 2.4,
 2,
 2,
 1.6,
 1.4,
 1.4,
 1.4,
 2.2,
 2.4,
 2,
 1.8,
 1.2,
 3,
 2,
 2.2,
 2.2,
 2.8,
 2.2,
 1.8,
 1.8,
 2.2,
 2.8,
 2.2,
 2.4,
 2,
 2.4,
 2.8,
 1.6,
 1.8,
 1.4,
 1.8,
 2.2,
 1.8,
 2,
 1.8,
 2.4,
 3,
 2.4,
 2.4,
 2,
 2.4,
 2.6,
 2,
 2.2,
 2.8,
 2.4,
 2.2,
 2,
 2,
 2.2,
 2.8,
 1.6,
 1.4,
 3,
 2,
 2.6,
 2.8,
 2.2,
 2.4,
 1.4,
 2,
 2.4,
 2.2,
 2,
 2.8,
 3.2,
 2.4,
 2.2,
 2.2,
 2.4,
 2.4,
 2.2,
 2.2,
 2,
 1.8,
 2.2,
 2.4,
 1.8,
 1.8,
 2.2,
 2.6,
 2.4,
 2.6,
 1.6,
 3.4,
 2.4,
 2,
 2.2,
 2.4,
 1.8,
 2,
 2.4,
 1.4,
 1.8,
 2.2,
 1.8,
 2,
 2,
 2,
 2.2,
 2.2,
 2.4,
 2.6,
 2,
 2.6,
 1.8,
 2.6,
 2.4,
 1.8,
 2,
 2.8,
 2,
 1.8,
 1.2,
 2,
 1.8,
 2.8,
 2,
 2,
 2,
 1.8,
 2,
 1.4,
 2.4,
 2.4,
 2,
 2,
 1.8,
 1.6,
 2.4,
 2,
 2,
 1.6,
 2.8,
 1.4,
 1.8,
 2.4,
 1.8,
 2.4,
 2,
 2.2,
 1.4,
 2.8,
 2.2,
 2,
 2.8,
 2,
 1.4,
 2.4,
 2.8,
 2,
 1.8,
 1.6,
 3,
 2.2,
 2.4,
 1.6,
 2,
 2,
 2.4,
 2.4,
 2.2,
 2,
 1.8,
 1.8,
 2.2,
 2.4,
 2.2,
 2,
 2.2,
 2.4,
 2.6,
 1.6,
 1.8,
 2,
 2.2,
 2.4,
 2.2,
 2.2,
 2.2,
 1.8,
 2.2,
 2,
 1.8,
 2.4,
 2.6,
 2.2,
 2.4,
 2.2,
 2.6,
 2.8,
 1.6,
 1.8,
 2.4,
 2.4,
 3,
 1.2,
 2,
 2.2,
 1.6,
 1.4,
 2.2,
 1.8,
 1.8,
 2.2,
 1.6,
 2.6,
 2.8,
 2.8,
 2.4,
 1.4,
 2.6,
 2.2,
 2.4,
 1.8,
 1.8,
 2.2,
 2,
 1.4,
 2.2]

In [32]:
import json

# Combine sentences and labels into a list of dictionaries
train_data = []
for i in range(1, 8):
	sentences = sentences_train_old_all[i]
	labels = labels_train_old_all[i]
	# make sure the labels are floats
	combined_data = [{'sentence': sentence, 'label': float(label)} for sentence, label in zip(sentences, labels)]
	train_data.append(combined_data)

# Save the data as JSON files
for i in range(1, 8):
	filename = f'train_data_{i}.json'
	with open(filename, 'w') as f:
		json.dump(train_data[i-1], f, ensure_ascii=False)

dev_data = []
for i in range(1, 8):
	sentences = sentences_dev_old_all[i]
	labels = labels_dev_old_all[i]
	combined_data = [{'sentence': sentence, 'label': float(label)} for sentence, label in zip(sentences, labels)]
	dev_data.append(combined_data)

# Save the data as JSON files
for i in range(1, 8):
	filename = f'dev_data_{i}.json'
	with open(filename, 'w') as f:
		json.dump(dev_data[i-1], f, ensure_ascii=False)

test_data = []
for i in range(1, 8):
	sentences = sentences_test_old_all[i]
	labels = labels_test_old_all[i]
	combined_data = [{'sentence': sentence, 'label': float(label)} for sentence, label in zip(sentences, labels)]
	test_data.append(combined_data)

# Save the data as JSON files
for i in range(1, 8):
	filename = f'test_data_{i}.json'
	with open(filename, 'w') as f:
		json.dump(test_data[i-1], f, ensure_ascii=False)